version: "3.8"

services:
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend:/opt/app
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      HOST: 0.0.0.0
      PORT: 1337
    depends_on:
      - postgres
    env_file: .env

  frontend:
    build: 
      context: ./frontend
    volumes:
      - .:/app  # Mount the current directory to the container
      - /app/node_modules  # Avoid mounting node_modules to prevent conflicts
    environment:
      - NODE_ENV=production
      - ./frontend/:/app/
    ports:
      - "3000:3000"


  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
